### ISSUE TITLE
quadratic_equation.hs

### ISSUE THREAD

**Issue by ankutalev** [Jlemix/v.leshkevich-18214#1]
1) sqroot a b c = sqrot a b c
               where sqrot a b c | a == 0 = error "Wrong inputs"
Тебе не кажется странной это конструкция?  Ну типа, а давайте summ a b = summm a b where summm a b =  a+b?

2) (вдогонку к 1) Дальше тоже как-то интересно: почему функция discriminant a b c через какие-то вложенные интересные конструкции ищет корни, а не просто считает дискриминант, я не особо понял. 
Убирай лишние вложенные функции, достаточно лишь одного дискриминанта.

3) (вдогонку к 2):
                   | b^2 - 4*a*c < 0 = error "No roots"
                   | b^2 - 4*a*c == 0 = roots a b c
                   | otherwise = roots a b c
Ничего не смущает здесь?
4)От функции, считающей корни квадратного уравнения, я хочу,чтобы она их возвращала мне, а не печатала - поэтому напалмом вычищаем do блок и забываем пока про putStrLn. 
Вывожу из ступора - чтобы из функции вернуть два значения, используй кортеж; пока - в гугл "хаскелл кортеж", в понедельник мы их рассмотрим подробно.
5)С чего это a=0 - invalid input? Я все-таки хочу узнать решение такого странного квадратного уравнения.

Если есть вопросы - пиши сюда в комментарии, после исправлений - тоже отпишись

**Comment by Jlemix** [comment]
В общем что-то подправил, да только все равно в чем-то ошибка.

По поводу a == 0, коэффициент ведь при первом слагаемом квадратного уравнения не может быть равным нулю, иначе получится линейное уравнение, разве не так?

**Comment by ankutalev** [comment]
>В общем что-то подправил, да только все равно в чем-то ошибка.
На глаз если смотреть, то ошибка в выравнивании охранных выражений, палки должны быть строго друг под другом. Ну и еще в том, что при нулевом дискриминанте ты возвращаешь не кортеж, а одиночное значение, функции в хаскеле так не умеют - в одних случаях возвращать кортеж, а в других - единичное значение. У нас тут приличный язык программирования, а не какой-нибудь ущербный перл.

Еще раз - дискриминант - это вложенная функция для подсчета **дискриминанта**, а не корней квадратного уравнения, этим как раз занимается внешняя функция sqroot, не нужно все обязанности внешней функции пихать во внутренние.

К тому же, посчитай сколько раз ты считаешь b^2 - 4*a*c , как-то явно больше одного, производишь слишком много ненужных повторных вычислений.

>По поводу a == 0, коэффициент ведь при первом слагаемом квадратного уравнения не может >быть равным нулю, иначе получится линейное уравнение, разве не так?

Все так, однако нормально написанные программы (а на фите только такие и учат писать) всегда работают корректно при любом пользовательском вводе и обычно политика такая - программа работает до тех пор, пока может, если уже совсем не может - то выдает пользователю, что что-то не то. В нашем случае программа при а==0 и b!=0 вполне  может работать

**Comment by Jlemix** [comment]
Исправил снова. Теперь, вроде как, всё работает как надо.

**Comment by ankutalev** [comment]
Ладно, принято
